<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.dsp</groupId>
  <artifactId>youdatax-dsp-core-spi</artifactId>
  <version>0.0.3.0</version>
  <name>yospace-dsp-spi</name>
  <description>yospace-dsp-spi</description>

  <dependencies>
<!--    api(project(":spi:control-plane:control-plane-spi"))-->
      <dependency>
        <groupId>com.yospace.controlplane</groupId>
        <artifactId>yospace-control-plane-spi</artifactId>  
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(project(":extensions:common:json-ld"))  
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld</artifactId>
        <version>0.18.0</version>
      </dependency>   -->
<!--    api(project(":spi:common:json-ld-spi"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld-spi</artifactId>
        <version>0.18.0</version>
      </dependency>      
      
   </dependencies>    
</project>