<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.dsp</groupId>
  <artifactId>youdatax-dsp-core-version-lib-transform</artifactId>
  <version>0.0.3.0</version>
  <name>yospace-dsp-core-version-transform-lib</name>
  <description>yospace-dsp-core-version-transform-lib</description>

  <dependencies>
<!--    api(project(":spi:common:core-spi"))-->
    
<!--    api(project(":spi:common:protocol-spi"))-->
    
<!--    api(project(":spi:common:json-ld-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId> 
        <artifactId>yospace-core-spi-json-ld</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>      
<!--    api(project(":spi:common:transform-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-lib-transform</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":data-protocols:dsp:dsp-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    

<!--    testImplementation(project(":core:common:junit"))-->
    
<!--    testImplementation(project(":extensions:common:json-ld"))-->
      
   </dependencies>    
</project>